spring.application.name=ms-personnel

server.port=8083

spring.datasource.url=jdbc:postgresql://postgres:5432/bibliotheque
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
